   default: &default
     adapter: mysql2
     encoding: utf8mb4
     pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
     port: 3306
     socket: /var/run/mysqld/mysqld.sock
     username: dev
     password: Root@123
     host: localhost

   development:
     <<: *default
     database: your_app_development

   test:
     <<: *default
     database: your_app_test

   production:
     <<: *default
     database: your_app_production
     username: your_production_username
     password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
